### PR TITLE
hwcomposer modelist changes are not applicable

### PR DESCRIPTION
**Pull request by bkothapx**
As no supported modelist from hwcomposer changes.
as code is not same and confilct were observed while patch applyin.

Tracked-On: OAM-108668

### CODE REVIEW

**Review by bnkoppad — APPROVED** [review]

**Review by basilchew — CHANGES_REQUESTED** [review]
Is this removing the commit from bsp_diff/caas/vendor/intel/utils_vertical_priv/0001-Revert-WA-to-retrieve-the-entire-supported-modelist-.patch?
Why can't we delete the patch instead?

**Review by bnkoppad — COMMENTED** [review]
@bkothapx  your previous commit deleted the patch right? why reverting now?

**Comment by bkothapx** [comment]
> @bkothapx your previous commit deleted the patch right? why reverting now?

Because of some miscommunication with integration team updated patch

CORRECTED now

**Comment by bkothapx** [comment]
> Is this removing the commit from bsp_diff/caas/vendor/intel/utils_vertical_priv/0001-Revert-WA-to-retrieve-the-entire-supported-modelist-.patch? Why can't we delete the patch instead?

updated the patch

**Review by basilchew — APPROVED** [review]

**Review by basilchew — CHANGES_REQUESTED** [review]
Please remove utils_vertical_priv folder too since there is not other patch

**Review by basilchew — APPROVED** [review]

**Pull request merged**
