### PR TITLE
Revert WA to retrieve the entire supported modelist from HwComposer

### PR DESCRIPTION
**Pull request by amudassx**
Set the default value to 0 for preferred modelist limited property

Tracked-On: OAM-108818

### CODE REVIEW

**Comment by amudassx** [comment]
Setting the property vendor.hwcomposer.preferred.mode.limit=1

TRACKED ON : OAM-108818

**Comment by amudassx** [comment]
Hello @basanagouda.nagappa.koppad@intel.com

Please review this patch.

**Review by bnkoppad — APPROVED** [review]

**Comment by amudassx** [comment]
Hello basil.chew@intel.com
Please review this patch.

**Review by kalyanalle — APPROVED** [review]
approved

**Comment by amudassx** [comment]
Hello @basil.chew@intel.com
Please review this patch

**Review by bnkoppad — APPROVED** [review]

**Review by XiaoHeSG — APPROVED** [review]

**Review by basilchew — APPROVED** [review]

**Pull request closed without merging**
