### PR TITLE
clang S fix for media_driver

### PR DESCRIPTION
**Pull request by vdanix**

### CODE REVIEW

**Comment by vdanix** [comment]
@tianmi.chen@intel.com kindly review the clang warning fix pr, let us know if these changes are barking any functionality.

**Review by TianmiChen — APPROVED** [review]

**Review by bnkoppad — CHANGES_REQUESTED** [review]
the code alignment in improper. Please correct it

**Comment by vdanix** [comment]
> the code alignment in improper. Please correct it

corrected code alignment.

**Comment by vdanix** [comment]
@basilchew please review the pr

**Comment by basilchew** [comment]
What is the corresponding Jira or PR for horizontal?

**Comment by vdanix** [comment]
> What is the corresponding Jira or PR for horizontal?

Horizontal jira : OAM-111285
Revert vertical jiar :OAM-111287

**Review by basilchew — APPROVED** [review]

**Pull request merged**
