### PR TITLE
horizontal WW10 rebase conflict resolution

### PR DESCRIPTION
**Pull request by pchenthx1**
Need to apply the re-implementation commit - 3319e5d from OAM-105855 after all the vertical patches to avoid conflicts and to apply this change cleanly

Tracked-On: OAM-107370

### CODE REVIEW

**Comment by pchenthx1** [comment]
Initialization code got refactored / re-implemented due to which, few of the vertical patches could not be applied. To resolve the conflicts in a cleaner way, moving the refined code introduced by OAM-105855 post vertical patches. Hence this resulted into "revert" of refined code and then "re-applying the refined code by performing revert on the previous revert commit"

Reviewers: @basilchew @bnkoppad kindly review

**Comment by pchenthx1** [comment]
Reviewers: @HeYue @chenyanxzhu @kalyanalle Please review

**Review by basilchew — CHANGES_REQUESTED** [review]
The merge conflicts starts appearing from patch 0007 for minigbm-intel vertical patches:

> 0005-Handle-DRM_IOCTL_I915_GEM_MMAP_GTT-failure-for-VF.patch
> 0006-Revert-if-is-not-kmsro-mode-only-destroy-driver-once.patch
> _**0007-Revert-support-open-up-to-two-backend-driver.patch         
> 0008-Zero-copy-changes-in-minigbm-gralloc-to-fix-the-andr.patch 
> 0009-limit-virtio-gpu-usage-only-for-scanout-and-compilat.patch 
> 0010-Added-back-if-it-is-not-kmsro-mode-only-destroy-driv.patch**_
> 

The patches were introduced by SRIOV team through OAM-102839:
- https://github.com/intel-innersource/os.android.bsp.vendor-intel-vertical-utils/commit/e16e0caaa2de5857a9670d97f7143eae2cfbbe7b

If you do the conflict resolution from merging the changes in 0009 and 0010, you will notice that it resembles the changes in OAM-105855:
- https://github.com/projectceladon/minigbm/pull/51/files

It is possible that the patches are made redundant by OAM-105855.
Have we engage the SRIOV team to check if 0008 to 0010 are still needed? Can they help with the rebase?

**Review by basilchew — CHANGES_REQUESTED** [review]
There are 5 patches introduced by OAM-102839, which includes 0006-Revert-if-is-not-kmsro-mode-only-destroy-driver-once.patch:
- https://github.com/intel-innersource/os.android.bsp.vendor-intel-vertical-utils/commit/e16e0caaa2de5857a9670d97f7143eae2cfbbe7b

Please check if it is also redundant

**Comment by pchenthx1** [comment]
> There are 5 patches introduced by OAM-102839, which includes 0006-Revert-if-is-not-kmsro-mode-only-destroy-driver-once.patch:
> 
> * [intel-innersource/os.android.bsp.vendor-intel-vertical-utils@e16e0ca](https://github.com/intel-innersource/os.android.bsp.vendor-intel-vertical-utils/commit/e16e0caaa2de5857a9670d97f7143eae2cfbbe7b)
> 
> Please check if it is also redundant

Yes, this is also not required

**Review by basilchew — APPROVED** [review]

**Pull request merged**
